# docker-compose.yml
version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./data/mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
        container_name: calendmap-mysql
    php:
        build: docker/php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - "./app:/var/www/symfony/app"
        container_name: calendmap-php
    nginx:
        build: docker/nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - "./var/log/nginx:/var/log/nginx"
        container_name: calendmap-nginx
    # Base NPM container that will be reuse to run NPM components such as webpack and vue.js (see next)
    base_npm:
        build: docker/npm
        environment:
            - NODE_ENV=dev
        volumes:
            - "./app:/var/www/symfony/app:rw"
        container_name: calendmap-npm