# docker-compose.yml
version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./data/mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
        container_name: calendmap-mysql
    php:
        build: docker/php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - ".:/var/www/symfony"
        container_name: calendmap-php
    nginx:
        build: docker/nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - "./var/log/nginx:/var/log/nginx"
        container_name: calendmap-nginx
    base_npm:
        build: docker/npm
        environment:
            - NODE_ENV=dev
        volumes:
            - "./app/node_modules:/home/node/app/node_modules"
        container_name: calendmap-npm
        tty: true
